services:
  vcenter-api:
    image: gitops.asax.ir/infrastructure-automation-team/virtualization-automation/vcenter-automation:slim
    container_name: vcenter-api
    command: python manage.py runserver 0.0.0.0:8000
    expose:
      - 8000
    networks:
      - traefik-net
    volumes:
      - ./vcenter_logs:/app/logs
      - ./vcenter_modules:/app/modules
    env_file:
      - ./.env
    environment:
      - TZ=Asia/Tehran
      - TF_VAR_vsphere_password=""
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-net
      - traefik.http.routers.vcenter_api.entrypoints=vcenter
      - traefik.http.routers.vcenter_api.rule=Host(`iaas-app.asax.ir`)
      - traefik.http.routers.vcenter_api.tls=true
      - traefik.http.routers.vcenter_api.tls.options=default
      - traefik.http.services.vcenter_api.loadbalancer.server.port=8000

networks:
    traefik-net:
      name: traefik-net
      external: true
