version: '3.7'
services:
  vcenter-api:
    image: vcenter-automation-api:latest
    container_name: vcenter-api
    command: python manage.py runserver_plus 0.0.0.0:8002 --cert-file ./certs/cert.pem --key-file ./certs/key.pem

    ports:
      - "8002:8002"
    env_file:
      - /opt/configs/vcenter_configs.env
    volumes:
      - /opt/vcenter_logs:/app/logs
      - /opt/vcenter_modules:/app/modules

